apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guestbook
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  # labels:
  #   app: redis
  #   role: master
  #   tier: backend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels:
  #     app: guestbook
  #     role: master
  #     tier: backend
  template:
    metadata:
      labels:
        app: guestbook
        tier: web
    spec:
      containers:
      - name: guestbook
        image: 192.168.1.10:5000/guestbook:{version}
#        resources:
#          requests:
#            cpu: 100m
#            memory: 100Mi
        ports:
        - containerPort: 3000
          name: http-server
